### ISSUE TITLE
Use a INI-like format for the Advanced Settings configuration comment

### ISSUE THREAD

**Issue by aspizu** [TurboWarp/scratch-vm#114]
The comment should look like this:
```toml
[Turbowarp Configuration]
frame_rate       = 60
interpolation    = true
high_quality_pen = true
warp_timer       = true
infinite_clones  = false
sprite_fencing   = false
misc_limits      = true
stage_width      = 720
stage_height     = 360
disable_compiler = true
```

#### Why?
The JSON configuration comment looks ugly.
Some people might prefer to configure Advanced Settings by editing the comment.

#### Another reason for this change ( The actual reason why I want this change )
To configure Advanced Settings in a [GoboScript](https://github.com/aspizu/goboscript) project, a comment like this needs to be added.
```
(*{"framerate":60,"hq":true} // _twconfig_*)
```

With this change, that comment will look like
```
(*
[Turbowarp Configuration]
frame_rate = 60
high_quality_pen = true
*)
```
